# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d718f87a2428913a693f6a98da5aa16ea4a1d74312e502b59a5cdb6dd5f8ad313330fe414babc2b60a28b673de1aef6b1ba51931a11ed89495389d488f585777

test:
  secret_key_base: d1e78bba5d78644d78fe6567ccd742f4b01326a86aff5d76b51a39874959cc5e9e97a94e8a6ce9382a528979574807d0b75bbd56a7ffa7e736656a30ed4d4628

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
